ci: test on more recent macOS (since older is no longer available)
This seemed to need a bump of the codecov upload action due to the error

> Error: spawn Unknown system error -86